import "./globals.css";

import Footer from "@/components/common/layout/Footer";
import Navbar from "@/components/desktop/layout/Navbar";
import { Metadata } from "next";
import {
  getLogoAndDesc,
  getNavItems,
  getCategories,
  getRange,
} from "@/apis/get-apis";
import { SidebarProvider } from "@/hooks/useSidebarMob";
import { ModalProvider } from "@/hooks/useModalContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  robots: {
    index: true,
    follow: true,
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //------PARALLEL DATA FETCHING FOR CRITICAL ELEMENTS--------------------
  const [navItems, logoAndDesc, categoryItems, productsRange] =
    await Promise.all([
      getNavItems(),
      getLogoAndDesc(),
      getCategories(),
      getRange(),
    ]);

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <div id="backdrop-root"></div>
        <div id="overlay-root"></div>
        <SidebarProvider>
          <ModalProvider>
            <div className="flex min-h-screen flex-col">
              <Navbar
                navData={navItems.menus[0]}
                logo={logoAndDesc.logo}
                categories={categoryItems}
                range={productsRange}
              />
              <div className="flex-1">{children}</div>
              <Footer
                socialLinks={navItems.menus[1]}
                quickLinks={navItems.menus[2]}
                resourceLinks={navItems.menus[3]}
                contactInfo={navItems.contact}
                logo={logoAndDesc.logo}
                description={logoAndDesc.logo_description}
              />
            </div>
          </ModalProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
